import { createSlice, PayloadAction } from '@reduxjs/toolkit';

// Define the state type for the counter slice
interface CounterState {
  value: number;
}

// Set the initial state
const initialState: CounterState = {
  value: 0,
};

// Create the counter slice
export const counterSlice = createSlice({
  name: 'counter', // Slice name
  initialState,
  reducers: {
    // Reducer for incrementing the counter
    increment: (state) => {
      state.value += 1; // Immer allows direct mutation within createSlice
    },
    // Reducer for decrementing the counter
    decrement: (state) => {
      state.value -= 1;
    },
    // Reducer for incrementing by a specific amount
    incrementByAmount: (state, action: PayloadAction<number>) => {
      state.value += action.payload;
    },
  },
});

// Export the action creators generated by createSlice
export const { increment, decrement, incrementByAmount } = counterSlice.actions;

// Export the reducer
export default counterSlice.reducer;